# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/process_reads.smk"
include: "rules/bowtie2.smk"
include: "rules/bwamem2.smk"
include: "rules/star.smk"
include: "rules/minimap2.smk"
include: "rules/mapping_stats.smk"
include: "rules/qc.smk"


# container definition (optional)
# -----------------------------------------------------
container: "oras://ghcr.io/mpusp/snakemake-simple-mapping:latest"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        "results/multiqc/multiqc_report.html"
    default_target: True
